config:
  target: "http://localhost:3000"
  phases:
    - duration: 60
      arrivalRate: 5
      rampTo: 20
      maxVusers: 100
  
scenarios:
  - name: "Browse products and view details"
    flow:
      - get:
          url: "/products"
      - think: 3
      - get:
          url: "/products/1"
