config:
  target: "http://localhost:3000"
  phases:
    - name: "Ramp up to peak"
      duration: 15 # Duration of the given phase in seconds.
      arrivalRate: 500 # Number of new users (Virtual Users) starting each second.
      rampTo: 100 # Target number of new users per second at the end of the phase (linear ramp-up/decline).
      maxVusers: 25000 # Hard limit for concurrently active virtual users.

    - name: "Sustain peak load"
      duration: 30
      arrivalRate: 500
      maxVusers: 25000

    - name: "Ramp down"
      duration: 15
      arrivalRate: 50
      rampTo: 0
      maxVusers: 25000

  variables:
    productId:
      - 1
      - 2
      - 3
      - 4
      - 5

scenarios:
  - name: "Browse products collection"
    flow:
      - get:
          url: "/products"
      - think: 2
      - get:
          url: "/products/{{ productId }}"
      - think: 1

  - name: "Create and manage product lifecycle"
    flow:
      - post:
          url: "/products"
          json:
            name: "Load Test Product"
            price: 49.99
          capture:
            - json: "$.id"
              as: createdProductId
      - think: 1
      - get:
          url: "/products/{{ createdProductId }}"
      - think: 1
      - delete:
          url: "/products/{{ createdProductId }}"
